
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from powerplant import PowerPlant

def display_graph(type: str, result_list: list, plants: list[PowerPlant]):
    if (type == 'cost'):
        return display_costopt_graph(result_list, plants)
    else: print('Error with display_graph function.')


def display_costopt_graph(mw_generated: list[int], plants: list[PowerPlant]):
    # from dr. logan's graph, x is plant names (with bar width mw drawn) and y is plant cost
    names = [p.name for p in plants]
    plant_costs = [p.plant_cost for p in plants]

    sorted_list: list[str, int, float] = []
    for i in range(len(plants)):
        if (mw_generated[i] != 0):
            sorted_list.append([names[i], mw_generated[i], plant_costs[i]])
    sorted_list = np.array(sorted_list)
    sorted_list = sorted_list[sorted_list[:,2].argsort()]

    names = [p[0] for p in sorted_list]
    mw_generated = [int(p[1]) for p in sorted_list]
    plant_costs = [float(p[2]) for p in sorted_list]

    colors = []
    for i in range(len(mw_generated)):
        colors.append(list(np.random.random(size=3)))

    # resizes bars to fit together nicely. adapted from https://stackoverflow.com/questions/70477458/how-can-i-plot-bar-plots-with-variable-widths-but-without-gaps-in-python-and-ad
    x_marks = []
    for i in range(len(mw_generated)):
        x_marks.append(sum(mw_generated[:i]) + (mw_generated[i]/2))

    # create graph
    graph = plt.bar(x_marks, height = plant_costs, width = mw_generated, color=colors)

    # graph/axis titles
    plt.title('mW Generated by Plant')
    plt.xlabel('Plant (width is amt of mW)')
    plt.ylabel('Plant Cost')

    # limits
    plt.xlim(left=0, right=sum(mw_generated))
    plt.ylim(bottom=0, top=((9/8) * max(plant_costs)))

    # misc
    plt.axhline(y=max(plant_costs), color='black', linestyle='-')  # horiz line to show wholesale cost/profit margins
    plt.legend(graph.patches, names, loc=4)
    
    # show graph
    plt.show()
