
import ctypes
import math
import matplotlib.colors as mpc
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import axes3d
import numpy as np
import pandas as pd
from powerplant import PowerPlant
from pymoo.visualization.scatter import Scatter
import sys
import win32api as wapi
import win32gui as wgui


popup_title_default = 'PyMOO Optimization'


def display_graph(type: str, **kwargs):
    match type:
        case 'cost_per_plant':      return display_costopt_graph(kwargs['result_list'], kwargs['plant_list'])
        case 'gen_vs_res':          return display_generation_graph(kwargs['history'])
        case 'multi_gen_vs_res':    return display_diffnum_generation_graph(kwargs['histories'])
        case 'cost_water_carbon':   
            if 'rotate' in kwargs and kwargs['rotate'] == True: return rotate_that_cube(kwargs['result'])
            else: return display_pareto(kwargs['result'])
        case _:                     print('Error with display_graph function.')


# this function just won't work if you're not on windows. ill add linux later. FUCK MAC RAHHHHHHHHH
def popup(message, title=popup_title_default):
    if sys.platform == 'win32': wgui.MessageBox(0, message, title, 0x01040040)
    elif sys.platform == 'linux': print(f'Linux popup implementation soon.')
    elif sys.platform == 'darwin': print(f'MacOS popup implementation soon. Maybe. I don\'t like MacOS.')
    else: print(f'Platform {sys.platform} has no plans for popup implementation.')


def display_costopt_graph(mw_generated: list[int], plants: list[PowerPlant]):
    # from dr. logan's graph, x is plant names (with bar width mw drawn) and y is plant cost
    if mw_generated.any():  # returns false if nothing in array, true if at least one item
        names = [p.name for p in plants]
        plant_costs = [p.plant_cost for p in plants]

        sorted_list: list[str, int, float] = []
        for i in range(len(plants)):
            if (mw_generated[i] != 0):
                sorted_list.append([names[i], mw_generated[i], plant_costs[i]])
        sorted_list = np.array(sorted_list)
        sorted_list = sorted_list[sorted_list[:,2].argsort()]

        names = [p[0] for p in sorted_list]
        mw_generated = [int(p[1]) for p in sorted_list]
        plant_costs = [float(p[2]) for p in sorted_list]

        colors = []
        for i in range(len(mw_generated)):
            colors.append(list(np.random.random(size=3)))
            # TODO make colors mean something? idk if i can here but we'll see

        # resizes bars to fit together nicely. adapted from https://stackoverflow.com/questions/70477458/how-can-i-plot-bar-plots-with-variable-widths-but-without-gaps-in-python-and-ad
        x_marks = []
        for i in range(len(mw_generated)):
            x_marks.append(sum(mw_generated[:i]) + (mw_generated[i]/2))

        # create graph
        graph = plt.bar(x_marks, height=plant_costs, width=mw_generated, color=colors)

        # graph/axis titles
        plt.title('mW Generated by Plant')
        plt.xlabel('Plant (width is amt of mW)')
        plt.ylabel('Plant Cost')

        # limits
        plt.xlim(left=0, right=sum(mw_generated))
        plt.ylim(bottom=0, top=((9/8) * max(plant_costs)))

        # misc
        plt.axhline(y=max(plant_costs), color='black', linestyle='-')  # horiz line to show wholesale cost/profit margins
        plt.legend(graph.patches, names, loc=4)
        
        # show graph
        plt.show()
    
    else: popup('Cannot graph results, no best solution was found.')


def display_generation_graph(history, rows=1, cols=1, plot_num=1, **kwargs):  # graph cost per generation. REQUIRED TO RUN ON MAIN THREAD
    # axis values
    xvals = [run.n_gen for run in history]
    yvals = [run.pop.get("F").min() for run in history]
    gvals = [run.pop.get("G").sum() for run in history]

    colors = []
    for cvsum in gvals:
        if cvsum > 0: colors.append('red')
        else: colors.append('green')

    plt.subplot(rows, cols, plot_num)
    plt.bar(xvals, yvals, color=colors)

    # graph/axis titles
    # plt.xlabel('Generation')
    # plt.ylabel('Cost (e10^6)')
    plt.title(f'{max(xvals)} Gens, F={int(yvals[max(xvals) - 1])}')

    if 'dontplotyet' not in kwargs:
        plt.show()


def display_diffnum_generation_graph(histories):
    num_graphs = len(histories)
    rows = int(math.sqrt(num_graphs)) + 1
    cols = int(num_graphs / rows) + 1

    for i, history in enumerate(histories):
        display_generation_graph(history, rows, cols, i+1, dontplotyet=True)

    # plt.tight_layout(pad=0.5)
    plt.subplots_adjust(left=0.05, right=0.95, 
                        top=0.9, bottom=0.0, 
                        wspace=0.2, hspace=0.55)
    plt.suptitle('Effects of Differing Numbers of Generations (x = Gens, y = Cost 1e6)')
    plt.show()


# TODO graph paretofront
def display_pareto(result):
    # adapted from https://pymoo.org/algorithms/moo/nsga2.html
    plt = Scatter(labels=['Cost ($million)', 'Water (L/kWh)', 'Carbon (L/kWh?)'])
    for dot in result:
        plt.add(dot)
    plt.show()


def rotate_that_cube(result):
    # adapted from https://matplotlib.org/stable/gallery/mplot3d/rotate_axes3d_sgskip.html
    fig = plt.figure()
    ax = fig.add_subplot(projection='3d')

    # # Grab some example data and plot a basic wireframe.
    # X, Y, Z = axes3d.get_test_data(0.05)
    # ax.plot_wireframe(X, Y, Z, rstride=10, cstride=10)

    # # Set the axis labels
    ax.set_xlabel('Cost ($million)')
    ax.set_ylabel('Water (L/kWh)')
    ax.set_zlabel('Carbon (L/kWh?)')

    xs = ys = zs = []

    # i know that this part works
    for dot in result:
        xs.append(float(dot[0]))
        ys.append(float(dot[1]))
        zs.append(float(dot[2]))

    ax.scatter3D(xs, ys, zs)

    # plt.show()

    # Rotate the axes and update
    for angle in range(0, 181):
        # Normalize the angle to the range [-180, 180] for display
        angle_norm = (angle + 180) % 360 - 180

        # Update the axis view and title
        ax.view_init(0, angle_norm)

        plt.draw()
        plt.pause(.001)

